package ASSignmmentMOdi.ASSignmmentMOdi;


public class payLoad {
	
	public static String AddPlace() {
		return "{[\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5317,\r\n"
				+ "    \"name\": \"AbulHashim\",\r\n"
				+ "    \"email\": \"Hashim_gupta@senger-mertz.com\",\r\n"
				+ "    \"gender\": \"male\",\r\n"
				+ "    \"status\": \"inactive\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5516,\r\n"
				+ "    \"name\": \"Chand Khatri\",\r\n"
				+ "    \"email\": \"chan_khatri@fisher-lakin.io\",\r\n"
				+ "    \"gender\": \"female\",\r\n"
				+ "    \"status\": \"actives\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5265,\r\n"
				+ "    \"name\": \"Es Gandhi\",\r\n"
				+ "    \"email\": \"gdhi_esha@abernathy.name\",\r\n"
				+ "    \"gender\": \"female\",\r\n"
				+ "    \"status\": \"inctive\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5614,\r\n"
				+ "    \"name\": \"Arata Mehra DDS\",\r\n"
				+ "    \"email\": \"aata_mehra_dds@brown.org\",\r\n"
				+ "    \"gender\": \"female\",\r\n"
				+ "    \"status\": \"active\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5213,\r\n"
				+ "    \"name\": \"Fr. eevakar Kaniyar\",\r\n"
				+ "    \"email\": \"devakar_fr_kaniyar@rowe-pollich.org\",\r\n"
				+ "    \"gender\": \"female\",\r\n"
				+ "    \"status\": \"inactive\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5912,\r\n"
				+ "    \"name\": \"Sroja Talwar\",\r\n"
				+ "    \"email\": \"tawar_saroja@damore-pagac.net\",\r\n"
				+ "    \"gender\": \"male\",\r\n"
				+ "    \"status\": \"inactive\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5561,\r\n"
				+ "    \"name\": \"Shakuntala Menon\",\r\n"
				+ "    \"email\": \"menon_shakuntala@macgyver.name\",\r\n"
				+ "    \"gender\": \"male\",\r\n"
				+ "    \"status\": \"inactive\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5228,\r\n"
				+ "    \"name\": \"Dr. Rukhmani Ahuja\",\r\n"
				+ "    \"email\": \"ahuja_dr_rukhmani@corkery-dickens.net\",\r\n"
				+ "    \"gender\": \"male\",\r\n"
				+ "    \"status\": \"inactive\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5179,\r\n"
				+ "    \"name\": \"Miss Vasudha Iyer\",\r\n"
				+ "    \"email\": \"miss_iyer_vasudha@daugherty-batz.biz\",\r\n"
				+ "    \"gender\": \"male\",\r\n"
				+ "    \"status\": \"active\"\r\n"
				+ "  },\r\n"
				+ "  {\r\n"
				+ "    \"id\": 5298,\r\n"
				+ "    \"name\": \"Nimit Joshi\",\r\n"
				+ "    \"email\": \"nimit_joshi@lindgren.com\",\r\n"
				+ "    \"gender\": \"female\",\r\n"
				+ "    \"status\": \"inactive\"\r\n"
				+ "  }\r\n"
				+ "]}"
				;
	}

}
